// <auto-generated />
using System;
using FILESMGMT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FILESMGMT.Migrations.FileDB
{
    [DbContext(typeof(FileDBContext))]
    [Migration("20240708064117_GAILFMSFileCreateDB")]
    partial class GAILFMSFileCreateDB : Migration // Ensure it inherits from Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) // Ensure the method signature is correct
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FILESMGMT.Models.Files", b =>
            {
                b.Property<int>("FileId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"), 1L, 1);

                b.Property<DateTime>("Closed_Date")
                    .HasColumnType("datetime2");

                b.Property<int>("Contract_No")
                    .HasColumnType("int");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasColumnName("Description");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FilePath")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<long>("FileSize")
                    .HasColumnType("bigint");

                b.Property<string>("File_type")
                    .IsRequired()
                    .HasColumnType("varchar(20)")
                    .HasColumnName("File Type");

                b.Property<DateTime>("Open_Date")
                    .HasColumnType("datetime2");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasColumnName("Status");

                b.Property<string>("Vendor_address")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Vendor_name")
                    .IsRequired()
                    .HasMaxLength(15)
                    .HasColumnType("nvarchar(15)");

                b.HasKey("FileId");

                b.ToTable("File");
            });
#pragma warning restore 612, 618
        }

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "File",
                columns: table => new
                {
                    FileId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Closed_Date = table.Column<DateTime>(nullable: false),
                    Contract_No = table.Column<int>(nullable: false),
                    Description = table.Column<string>(type: "varchar(100)", nullable: false),
                    FileName = table.Column<string>(nullable: false),
                    FilePath = table.Column<string>(nullable: false),
                    FileSize = table.Column<long>(nullable: false),
                    File_type = table.Column<string>(type: "varchar(20)", nullable: false),
                    Open_Date = table.Column<DateTime>(nullable: false),
                    Status = table.Column<string>(type: "varchar(100)", nullable: false),
                    Vendor_address = table.Column<string>(nullable: false),
                    Vendor_name = table.Column<string>(maxLength: 15, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_File", x => x.FileId);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "File");
        }
    }
}
