// <auto-generated />
using FILESMGMT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FILESMGMT.Migrations
{
    [DbContext(typeof(VendorDBContext))]
    partial class VendorDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FILESMGMT.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"), 1L, 1);

                    b.Property<string>("ContactEmailId")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contactemail");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("contactno");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contactperson");

                    b.Property<string>("VendorAddress")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("vendoraddress");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vendorname");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
