// <auto-generated />
using FILESMGMT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GAILFileManagementSystem.Migrations
{
    [DbContext(typeof(FileDBContext))]
    partial class FileDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FILESMGMT.Models.Files", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"), 1L, 1);

                    b.Property<string>("Closed_Date")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Closed_Date");

                    b.Property<int>("Contract_No")
                        .HasColumnType("int")
                        .HasColumnName("Contract_No");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Description");

                    b.Property<string>("File_type")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("File Type");

                    b.Property<string>("Open_Date")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Open_Date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Status");

                    b.Property<string>("Vendor_address")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Vendor_address");

                    b.Property<string>("Vendor_name")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Vendor_name");

                    b.HasKey("FileId");

                    b.ToTable("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
