// <auto-generated />
using System;
using GAILFileManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GAILFileManagementSystem.Migrations
{
    [DbContext(typeof(myDbContext))]
    partial class myDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GAILFileManagementSystem.Models.ConsolidatedReportViewModel", b =>
                {
                    b.Property<int>("FILE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FILE_ID"), 1L, 1);

                    b.Property<DateTime>("CLOSED_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CONTACT_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTACT_PERSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTRACT_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CONTRACT_END_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("CONTRACT_ID")
                        .HasColumnType("int");

                    b.Property<string>("CONTRACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CONTRACT_START_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CONTRACT_SUBJECT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTRACT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContractSNO")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILE_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILE_STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FILE_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FilesFILE_ID")
                        .HasColumnType("int");

                    b.Property<int>("GSTN_NO")
                        .HasColumnType("int");

                    b.Property<int>("LOCATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("LOCATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationL_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OPEN_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int>("SUBLOCATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("SUBLOCATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VENDOR_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VENDOR_ID")
                        .HasColumnType("int");

                    b.Property<int?>("VENDOR_ID1")
                        .HasColumnType("int");

                    b.Property<string>("VENDOR_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FILE_ID");

                    b.HasIndex("ContractSNO");

                    b.HasIndex("FilesFILE_ID");

                    b.HasIndex("LocationL_ID");

                    b.HasIndex("VENDOR_ID1");

                    b.ToTable("ConsolidatedReportViewModel");
                });

            modelBuilder.Entity("GAILFileManagementSystem.Models.Contract", b =>
                {
                    b.Property<int>("SNO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SNO"), 1L, 1);

                    b.Property<string>("CONTRACT_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTRACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTRACT_SUBJECT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CONTRACT_TYPE")
                        .HasColumnType("int");

                    b.Property<DateTime>("END_DATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("START_DATE")
                        .HasColumnType("datetime2");

                    b.HasKey("SNO");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("GAILFileManagementSystem.Models.Files", b =>
                {
                    b.Property<int>("FILE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FILE_ID"), 1L, 1);

                    b.Property<DateTime>("CLOSED_DATE")
                        .HasColumnType("datetime")
                        .HasColumnName("CLOSED_DATE");

                    b.Property<string>("CONTACT_EMAIL")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CONTACT_EMAIL");

                    b.Property<string>("CONTACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTACT_PERSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTRACT_DESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTRACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTRACT_SUBJECT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CONTRACT_TYPE")
                        .HasColumnType("int");

                    b.Property<int?>("ContractSNO")
                        .HasColumnType("int");

                    b.Property<string>("DESCRIPTION")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTime>("END_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("FILE_NAME")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FILE_NAME");

                    b.Property<string>("FILE_TYPE")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("FILE_TYPE");

                    b.Property<int>("GSTN_NO")
                        .HasColumnType("int");

                    b.Property<int>("LOCATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("LOCATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("L_ID")
                        .HasColumnType("int");

                    b.Property<int?>("LocationL_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OPEN_DATE")
                        .HasColumnType("datetime")
                        .HasColumnName("OPEN_DATE");

                    b.Property<int>("SNO")
                        .HasColumnType("int");

                    b.Property<DateTime>("START_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("STATUS");

                    b.Property<int>("SUBLOCATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("SUBLOCATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VENDOR_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VENDOR_ID")
                        .HasColumnType("int");

                    b.Property<int?>("VENDOR_ID1")
                        .HasColumnType("int");

                    b.Property<string>("VENDOR_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FILE_ID");

                    b.HasIndex("ContractSNO");

                    b.HasIndex("LocationL_ID");

                    b.HasIndex("VENDOR_ID1");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("GAILFileManagementSystem.Models.Location", b =>
                {
                    b.Property<int>("L_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("L_ID"), 1L, 1);

                    b.Property<int>("GSTN_NO")
                        .HasColumnType("int");

                    b.Property<int>("LOCATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("LOCATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SUBLOCATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("SUBLOCATION_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("L_ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GAILFileManagementSystem.Models.Vendor", b =>
                {
                    b.Property<int>("VENDOR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VENDOR_ID"), 1L, 1);

                    b.Property<string>("CONTACT_EMAIL")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CONTACT_EMAIL");

                    b.Property<string>("CONTACT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTACT_PERSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VENDOR_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VENDOR_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VENDOR_ID");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("GAILFileManagementSystem.Models.ConsolidatedReportViewModel", b =>
                {
                    b.HasOne("GAILFileManagementSystem.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractSNO");

                    b.HasOne("GAILFileManagementSystem.Models.Files", "Files")
                        .WithMany()
                        .HasForeignKey("FilesFILE_ID");

                    b.HasOne("GAILFileManagementSystem.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationL_ID");

                    b.HasOne("GAILFileManagementSystem.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VENDOR_ID1");

                    b.Navigation("Contract");

                    b.Navigation("Files");

                    b.Navigation("Location");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("GAILFileManagementSystem.Models.Files", b =>
                {
                    b.HasOne("GAILFileManagementSystem.Models.Contract", "Contract")
                        .WithMany("Files")
                        .HasForeignKey("ContractSNO");

                    b.HasOne("GAILFileManagementSystem.Models.Location", "Location")
                        .WithMany("Files")
                        .HasForeignKey("LocationL_ID");

                    b.HasOne("GAILFileManagementSystem.Models.Vendor", "Vendor")
                        .WithMany("Files")
                        .HasForeignKey("VENDOR_ID1");

                    b.Navigation("Contract");

                    b.Navigation("Location");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("GAILFileManagementSystem.Models.Contract", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("GAILFileManagementSystem.Models.Location", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("GAILFileManagementSystem.Models.Vendor", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
